export {default as About} from './About.page'
export {default as Contact} from './Contact.page'
export {default as Join} from './Join.page'
export {default as Landing} from './Landing.page'
export {default as Projects} from './Projects.page'
export {default as Teams} from './Teams.page'
export {default as Main} from './Main.page'
export {default as JobOffer} from './JobOffer.page'